@host = http://localhost:5000

@access_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJlbWFpbCI6IkRldm9uMTdAeWFob28uY29tIiwiZmlyc3RuYW1lIjoiw4lsZXV0aMOocmUiLCJsYXN0bmFtZSI6IlJveSIsInBzZXVkbyI6IsOJbGV1dGjDqHJlIiwicGhvbmVfbnVtYmVyIjoiMDUxODg4OTY1MSIsImF2YXRhciI6Imh0dHBzOi8vcmVzLmNsb3VkaW5hcnkuY29tL29wYXJhZGlzL2ltYWdlL3VwbG9hZC93XzIwMCxoXzIwMCxjX2ZpbGwsZ19mYWNlLHJfbWF4L3YxNjQ0MjQ4MTk3L2F2YXRhcnMvdmVja29paXJkYWhlenpxeXF5N2YuanBnIiwiaXNhZG1pbiI6ZmFsc2UsImNyZWF0ZWRfYXQiOiIyMDIyLTA0LTA0VDEyOjQ5OjE3LjE1M1oiLCJ1cGRhdGVkX2F0IjoiMjAyMi0wNC0wNFQxMjo0OToxNy4xNTNaIiwiaG91c2UiOlt7ImlkIjoyfV0sImFuaW1hbCI6W3siaWQiOjEwM30seyJpZCI6MTA0fSx7ImlkIjoxMDV9XSwicGxhbnQiOlt7ImlkIjoxMDN9LHsiaWQiOjEwNH0seyJpZCI6MTA1fV0sInBob3RvIjpbeyJpZCI6MTA1fSx7ImlkIjoxMDZ9LHsiaWQiOjEwN30seyJpZCI6MTA4fV0sImFic2VudGVlIjpudWxsfSwiaWF0IjoxNjQ5MDgyNDMwLCJleHAiOjE2NDkwODI0MzV9.cKrN_EnmZu1kwyCIhl6DbliMzBBCqw6kHnEiKB-7uZo
@refresh_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyLCJlbWFpbCI6IkRldm9uMTdAeWFob28uY29tIiwiZmlyc3RuYW1lIjoiw4lsZXV0aMOocmUiLCJsYXN0bmFtZSI6IlJveSIsInBzZXVkbyI6IsOJbGV1dGjDqHJlIiwicGhvbmVfbnVtYmVyIjoiMDUxODg4OTY1MSIsImF2YXRhciI6Imh0dHBzOi8vcmVzLmNsb3VkaW5hcnkuY29tL29wYXJhZGlzL2ltYWdlL3VwbG9hZC93XzIwMCxoXzIwMCxjX2ZpbGwsZ19mYWNlLHJfbWF4L3YxNjQ0MjQ4MTk3L2F2YXRhcnMvdmVja29paXJkYWhlenpxeXF5N2YuanBnIiwiaXNhZG1pbiI6ZmFsc2UsImNyZWF0ZWRfYXQiOiIyMDIyLTA0LTA0VDEyOjQ5OjE3LjE1M1oiLCJ1cGRhdGVkX2F0IjoiMjAyMi0wNC0wNFQxMjo0OToxNy4xNTNaIiwiaG91c2UiOlt7ImlkIjoyfV0sImFuaW1hbCI6W3siaWQiOjEwM30seyJpZCI6MTA0fSx7ImlkIjoxMDV9XSwicGxhbnQiOlt7ImlkIjoxMDN9LHsiaWQiOjEwNH0seyJpZCI6MTA1fV0sInBob3RvIjpbeyJpZCI6MTA1fSx7ImlkIjoxMDZ9LHsiaWQiOjEwN30seyJpZCI6MTA4fV0sImFic2VudGVlIjpudWxsfSwiaWF0IjoxNjQ5MDgyNDMwLCJleHAiOjE2NDkwODI0NDB9.cQizE1JgGENellsLToj5Af7Uvtnct1QAdf6diC5Qyxs
@avatar = data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAaCAIAAAAi3QukAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABCSURBVEhLrccxDQAwDMCw8odRdIWxP6c1yY9n9v7oWc961rOe9axnPetZz3rWs571rGc961nPetaznvWsZz3rzd4DxkTAjrVWJ/YAAAAASUVORK5CYII=
POST {{host}}/signup HTTP/1.1
content-type: application/json

{
    "email": "o@p.com",
    "password": "Paradis13$",
    "repeat_password": "Paradis13$",
    "firstname": "o",
    "lastname": "o",
    "pseudo": "Jacquou le croquant",
    "phone_number": "0184546417",
    "avatar": ""
}

### Connexion User
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "Devon17@yahoo.com",
    "password": "JNRBS08WX8L584TU7"
}

### Update Password
PATCH {{host}}/customers/102/password HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

{
    "ancient_password": "Paradis12$",
    "password": "Paradis13$",
    "repeat_password": "Paradis13$"
}

###
POST {{host}}/token HTTP/1.1
content-type: application/json
Authorization: {{refresh_token}}

###
DELETE {{host}}/logout HTTP/1.1
content-type: application/json
Authorization: {{refresh_token}}